print("The Zen of Python, by Tim Peters\n")
print("Beautiful is better than ugly.\nExplicit is better than implicit.")
print("Simple is better than complex.\nComplex is better than complicated.")
print("Flat is better than nested.\nSparse is better than dense.\nReadability counts.")
print("Special cases aren't special enough to break the rules.\nAlthough practicality beats purity.")
print("Errors should never pass silently.\nUnless explicitly silenced.")
print("In the face of ambiguity, refuse the temptation to guess.")
print("There should be one-- and preferably only one --obvious way to do it.")
print("Although that way may not be obvious at first unless you're Dutch.")
print("Now is better than never.\nAlthough never is often better than *right* now.")
print("If the implementation is hard to explain, it's a bad idea.")
print("If the implementation is easy to explain, it may be a good idea.")
print("Namespaces are one honking great idea -- let's do more of those!")
